### ISSUE TITLE
just a sugestion not want to promote or any thing my u can see my repo for a nice approche 

### ISSUE THREAD

**Issue by meetkool** [scidsg/onion-service#1]
just a sugestion not want to promote or any thing my u can see my repo for a nice approche 

https://github.com/meetkool/CloudCapsule

**Comment by meetkool** [comment]
i think u should my project that is now like hosting paas hosting thing but 

my approch is that forany hosting client they will get 2 urls private and public private is  the dashboard thing and public is the actual url 

u can do it like after the docker container is running  with ONION_HOSTNAME , ONION_PUBLIC_KEY_B64 and ONION_SECRET_KEY_B64 

and it will not only pass the the onion serivce but also generate a different private url that has ssh access also and ur public link that u provided will not have ssh or any thing it will block it 

i wrote this project 3-2 year ago i am now learned to write it better 

it is just a  suggestion that ppl use on tor network a lote idk

**Comment by brassy-endomorph** [comment]
Closed as off topic.
